
#include<system.h>
#include<alt_types.h>

// For Accelerometer sensor
#define MPU_SLAVE_ADDRESS 0x68

#define I2C_SLAVE_ADDR (MP6050_0_BASE | 0x80000000)
#define I2C_REG_ADDR (I2C_SLAVE_ADDR + 1)
#define I2C_REG_WRITE_DATA (I2C_SLAVE_ADDR + 2)
#define I2C_DATALENGTH_ADDR (I2C_SLAVE_ADDR + 3)
#define I2C_CMD_ADDR (I2C_SLAVE_ADDR + 4)
#define I2C_DATA_AVAILABLE_ADDR (I2C_SLAVE_ADDR + 8)
#define I2C_READ_CMD_MASK 0x01
#define I2C_WRITE_CMD_MASK 0x00
#define I2C_START_CMD_MASK 0x02

// For Ultrasound sensor
#define ULTRA_SOUND_READY_ADDR HC_SR04_0_BASE
#define ULTRA_SOUND_TRIG_ADDR  HC_SR04_0_BASE
#define ULTRA_SOUND_TRIG_ALL_CMD  0xFF
#define ULTRA_SOUND_READY_ALL_MASK  0xFF
#define NUMBER_OF_ULTRA_SOUND_DEVICES 8
#define ULTRA_SOUND_RESOLUTION 6 // 0.3 cm resolution + 0.3 cm tolerance
#define ULTRA_SOUND_0_TRIG_CMD    0x1
#define ULTRA_SOUND_0_READY_MASK    0x1
#define ULTRA_SOUND_1_TRIG_CMD    0x2
#define ULTRA_SOUND_1_READY_MASK    0x2
#define ULTRA_SOUND_2_TRIG_CMD    0x4
#define ULTRA_SOUND_2_READY_MASK    0x4
#define ULTRA_SOUND_3_TRIG_CMD    0x8
#define ULTRA_SOUND_3_READY_MASK    0x8
#define ULTRA_SOUND_4_TRIG_CMD    0x10
#define ULTRA_SOUND_4_READY_MASK    0x10
#define ULTRA_SOUND_5_TRIG_CMD    0x20
#define ULTRA_SOUND_5_READY_MASK    0x20
#define ULTRA_SOUND_6_TRIG_CMD    0x40
#define ULTRA_SOUND_6_READY_MASK    0x40
#define ULTRA_SOUND_7_TRIG_CMD    0x80
#define ULTRA_SOUND_7_READY_MASK    0x80

#define ULTRA_SOUND_0_READING_ADDR  ULTRA_SOUND_TRIG_ADDR+4
